// <auto-generated />
using System;
using CampusFeedApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CampusFeedApi.Migrations
{
    [DbContext(typeof(CampusFeedInfoDataContext))]
    [Migration("20240117225625_InitializeMigrate")]
    partial class InitializeMigrate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("CampusFeedApi.Models.CampusFeedInfo", b =>
                {
                    b.Property<string>("CampusFeedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Dislike")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Like")
                        .HasColumnType("INTEGER");

                    b.HasKey("CampusFeedId");

                    b.ToTable("CampusFeedInfo", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
